site_name: Culinary Program Wiki
theme:
  name: material
  features:
    - navigation.tabs        # Top-level tabs: Core | Food & Nutrition | Culinary 1 | Culinary 2
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default

plugins:
  - search
  - tags
  - awesome-pages
  - glightbox
  - git-revision-date-localized:
      type: date
  - macros
  - callouts
  - exclude:
      glob:
        - drafts/*
  - print-site